// AUTO-GENERATED by scripts/generate-audio.js
// Do not edit manually. Run the audio generation workflow to update.
//
// Until the workflow runs, this map is empty and the app falls back to TTS.

export const AUDIO_ASSETS: Record<string, any> = {};
